import math
from unicodedata import name
print("Задача 1")
a = int(input("Введіть перче число: "))
b = int(input("Введіть друге число: "))
c = int(input("Введіть третє число: "))
chus = min(a,b,c)
chus1 = max(a,b,c)
print("Найбільше число: "+str(chus1)+" , а найменше число: "+str(chus))
print("Задача 2")
a = int(input("Введіть число а: "))
n = input("1 чи 2: ")
if n == "1":
    x = a/7
elif n == "2":
    x = int((4+a)/(4+a))
print("х = " + str(round(x,1)))
print("Задача 3")
a = int(input("Введіть число яке треба перевести: "))
print("У двійковій системі ваше число має вигляд: "+ str(bin(a)) +" , а у десятковій: "+ str(hex(a))+" , а у восмирічній: "+str(oct(a)))
print("Перевіремо чи виведе навпаки: "+ str(int(bin(a),2))+" "+str(int(float.fromhex(hex(a)))))
print("Задача 4")
txt = input("Введіть якийсь текст: ")
a = int(input("Введіть якесь ціле число: "))
b =  (a * txt)
c = txt + str((a - 1))
d = (a * + 4 - 5) * txt
print("Ось, що вийшло: "+"|"+str(b)+"|"+"|"+str(c)+"|"+"|"+str(d)+"|")
print("Задача 5")
a = int(input("Введіть число a: "))
b = int(input("Введіть число b: "))
num_1 = math.pow(a,b)
num_2 = math.pow(b,a)
num_3 = math.pow(a,b-1)
num_4 = math.pow(b,a-1)
num_5 = math.pow(a*b,a+b)
print("Ось, що вишло: квадрат b = " + str(int(num_1)) + " квадрат a = " + str(int(num_2)) + " квадрат b-1 = " + str(int(num_3)) + " квадрат a-1 = " + str(int(num_4)) + " квадрат a+b = " + str(int(num_5)))
print("Задача 6")
fac = str(math.factorial(int(input("Введіть число: "))))
print("Ваше число: " + fac)
print("Задача 7")
fac_1 = math.factorial(int(input("Введіть число: ")))
fac_2 = math.factorial(int(input("Введіть число: ")))
fac = fac_1 + fac_2
print("В резутаті сума факторіалів цих чисел дорівнює: " + str(fac))
print("Задача 8")
a = int(input("Введіть радіус: "))
a *= 2
a_col = str(round((a**2 * math.pi), 2))
a_dov = str(round((2 * a * math.pi), 2))
print("Площа кола = "+a_col+" , а довжина кола = "+a_dov)
print("Задача 9")
name = input("Введіть ім'я спортсмена: ")
number = input("Введіть його номер: ")
point_1 = int(input("Введіть скільки він отримав білів в 1 змаганні: "))
point_2 = int(input("Введіть скільки він отримав білів в 2 змаганні: "))
point_3 = int(input("Введіть скільки він отримав білів в 3 змаганні: "))
sr = ((point_1+point_2+point_3)/3)* 0.6
max = max(point_1,point_2,point_3)
print(f"Спортсмен {name} під номером {number}, який набрав на першому зманагі {point_1}, на другому {point_2} та на третьому {point_3} балів. Найвищий результат {max}. Середня кількість балів {sr}.")
print("Задача 10")
nam = input("Введіть те, що бажаете придбати: ")
sum = int(input("Введіть скільце це буде коштувати: "))
spl = round((sum * 0.3),1)
spl_1 = round(((sum*0.7)/6),1)
print(f"Ви бажаєте придбати {nam}. Це буде коштувати: {sum}. Спосіб сплати: сплачуєте 30% від суми при купівлі {spl} а решту – 6-ма однаковими платежами {spl_1}")