a = '120'
b = int(a)
a1 = 37.73
b1 = str(a1)
a2 = (45+5)*2
b2 = str(a2)
a3 = (67+3)/2
b3 = float(a3)
a4 = 12.6
b4 = int(a4)
print("Тип даних a = "+str(a)+" становить: "+str(type(a)))
print("Тип даних b = "+str(b)+" становить: "+str(type(b)))
print("Тип даних a1 = "+str(a1)+" становить: "+str(type(a1)))
print("Тип даних b1 = "+str(b1)+" становить: "+str(type(b1)))
print("Тип даних a2 = "+str(a2)+" становить: "+str(type(a2)))
print("Тип даних b2 = "+str(b2)+" становить: "+str(type(b2)))
print("Тип даних a3 = "+str(a3)+" становить: "+str(type(a3)))
print("Тип даних b3 = "+str(b3)+" становить: "+str(type(b3)))
print("Тип даних a4 = "+str(a4)+" становить: "+str(type(a4)))
print("Тип даних b4 = "+str(b4)+" становить: "+str(type(b4)))